Use volatile to workaround buffer overflow false positives.
jemalloc/jemalloc pull request #2244
Opened 2022-03-23 23:38 UTC by interwq

In test/integration/rallocx, full usable size is checked which may confuse
overflow detection.

re: #2238

2022-03-25 00:07 UTC, Lapenkov commented
Do we have a confirmation that this fixes the issue?

2022-03-25 00:34 UTC, interwq commented
No I haven't got gcc 12 yet. @marxin could you help to verify if this PR fixes the issue?

2022-03-25 14:09 UTC, marxin commented
> No I haven't got gcc 12 yet. @marxin could you help to verify if this PR fixes the issue?

Yes, I can confirm that.

2022-03-25 14:09 UTC, marxin requested changes

2022-03-25 14:09 UTC, marxin commented on test/integration/rallocx.c
> +	/* Use volatile to workaround buffer overflow false positives. */
Please document the change is related to `-D_FORTIFY_SOURCE`.

2022-03-26 06:49 UTC, marxin approved these changes

2022-04-04 19:14 UTC, Lapenkov approved these changes

2022-04-04 19:16 UTC, merged